# Final Project Update - Tidied Dataset Assignment

## Dataset 1

- This dataset came from https://healthdata.gov/
- Here is where you can download the raw dataset:
https://healthdata.gov/dataset/Use-of-Telemedicine-During-COVID-19/c835-etjt
- Here is where you can download the tidied dataset:
https://docs.google.com/spreadsheets/d/1nLVdQnSvLo_WF9kW5ozSGuFCKxmIfQKSbzPAr1-AhT0/edit?usp=sharing
- I tidied my dataset by eliminating the "Round," "Suppression" and "Significant" rows, because I didn't feel they added or contributed enough of what I needed for my story. I also organized the columns and rows better so the data was more readable.
- Originally, I asked the question, "What is the background of how they sampled people for this?" I don't think I'm going to get a super clear answer since it appears to be random.
- This data supports the story I'm telling by showing the demographics of individual people who had or did not have telehealth access.

### Raw Dataset

In [32]:
dfRaw1 = pd.read_csv("Use_of_Telemedicine_During_COVID-19.csv")

In [33]:
dfRaw1.head(10)

,Round,Indicator,Group,Subgroup,Sample Size,Response,Percent,Standard Error,Suppression,Significant
0,1,Provider offers telemedicine,Total,Total,6786.0,Total,100.0,NaN,NaN,NaN
1,1,Provider offers telemedicine,Total,Total,NaN,Yes,36.6,0.8,NaN,NaN
2,1,Provider offers telemedicine,Total,Total,NaN,No,46.9,0.8,NaN,NaN
3,1,Provider offers telemedicine,Total,Total,NaN,Do not know,5.2,0.4,NaN,NaN
4,1,Provider offers telemedicine,Total,Total,NaN,No usual place of care,11.3,0.7,NaN,NaN
5,1,Provider offers telemedicine,Age group,18-44 years,2607.0,Total,100.0,NaN,NaN,NaN
6,1,Provider offers telemedicine,Age group,18-44 years,NaN,Yes,30.2,1.2,NaN,NaN
7,1,Provider offers telemedicine,Age group,18-44 years,NaN,No,45.9,1.1,NaN,NaN
8,1,Provider offers telemedicine,Age group,18-44 years,NaN,Do not know,7.0,0.8,NaN,NaN
9,1,Provider offers telemedicine,Age group,18-44 years,NaN,No usual place of care,16.9,1.1,NaN,NaN

In [34]:
dfRaw1.tail(10)

,Round,Indicator,Group,Subgroup,Sample Size,Response,Percent,Standard Error,Suppression,Significant
522,2,Provider offered telemedicine prior to pandemic,Chronic conditions,Diagnosed hypertension,2181.0,Total,100.0,NaN,NaN,NaN
523,2,Provider offered telemedicine prior to pandemic,Chronic conditions,Diagnosed hypertension,NaN,Yes,16.0,1.0,NaN,0.0
524,2,Provider offered telemedicine prior to pandemic,Chronic conditions,Diagnosed hypertension,NaN,No,67.9,1.4,NaN,0.0
525,2,Provider offered telemedicine prior to pandemic,Chronic conditions,Diagnosed hypertension,NaN,Do not know,10.8,0.9,NaN,0.0
526,2,Provider offered telemedicine prior to pandemic,Chronic conditions,Diagnosed hypertension,NaN,No usual place of care,5.3,0.6,NaN,0.0
527,2,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,618.0,Total,100.0,NaN,NaN,NaN
528,2,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,Yes,16.0,1.2,NaN,0.0
529,2,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,No,63.6,2.2,NaN,0.0
530,2,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,Do not know,11.8,2.3,NaN,0.0
531,2,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,No usual place of care,8.6,1.4,NaN,0.0

In [35]:
dfRaw1.shape

(532, 10)

### Tidied Dataset

In [28]:
import pandas as pd

In [41]:
dfTidied1 = pd.read_csv("Use_of_Telemedicine_During_COVID-19 - Tidied - Dataset 1.csv")

In [42]:
dfTidied1.head(10)

,Unnamed: 0,Indicator,Group,Subgroup,Sample Size,Response,Percent,Standard Error
0,NaN,Provider offers telemedicine,Total,Total,6786.0,Total,100.0,NaN
1,NaN,Provider offers telemedicine,Total,Total,NaN,Yes,36.6,0.8
2,NaN,Provider offers telemedicine,Total,Total,NaN,No,46.9,0.8
3,NaN,Provider offers telemedicine,Total,Total,NaN,Do not know,5.2,0.4
4,NaN,Provider offers telemedicine,Total,Total,NaN,No usual place of care,11.3,0.7
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Provider offers telemedicine,Age group,18-44 years,2607.0,Total,100.0,NaN
7,NaN,Provider offers telemedicine,Age group,18-44 years,NaN,Yes,30.2,1.2
8,NaN,Provider offers telemedicine,Age group,18-44 years,NaN,No,45.9,1.1
9,NaN,Provider offers telemedicine,Age group,18-44 years,NaN,Do not know,7.0,0.8

In [43]:
dfTidied1.tail(10)

,Unnamed: 0,Indicator,Group,Subgroup,Sample Size,Response,Percent,Standard Error
276,NaN,Provider offered telemedicine prior to pandemic,Chronic conditions,Diagnosed hypertension,2419.0,Total,100.0,NaN
277,NaN,Provider offered telemedicine prior to pandemic,Chronic conditions,Diagnosed hypertension,NaN,Yes,15.1,1.0
278,NaN,Provider offered telemedicine prior to pandemic,Chronic conditions,Diagnosed hypertension,NaN,No,68.2,1.3
279,NaN,Provider offered telemedicine prior to pandemic,Chronic conditions,Diagnosed hypertension,NaN,Do not know,10.8,1.1
280,NaN,Provider offered telemedicine prior to pandemic,Chronic conditions,Diagnosed hypertension,NaN,No usual place of care,5.9,0.7
281,NaN,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,698.0,Total,100.0,NaN
282,NaN,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,Yes,18.3,2.0
283,NaN,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,No,64.3,1.8
284,NaN,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,Do not know,9.1,1.4
285,NaN,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,No usual place of care,8.2,1.6

In [45]:
dfTidied1.shape

(286, 8)

## Dataset 2

- This dataset came from https://www.cdc.gov/
- Here is where you can download the raw dataset:
https://www.cdc.gov/mmwr/volumes/69/wr/pdfs/mm6950a4-H.pdf
- Here is a link to the tidied dataset: https://docs.google.com/spreadsheets/d/1X9FVBh0FXyrGSyp_DulSDnjRryO6CyhnzHruxxpXYwg/edit?usp=sharing
- I honestly did not feel the dataset needed to be tidied. It made clear sense and I didn't want to eliminate too much important information.
- Originally, I asked the question, "What do these categories mean?" I found out what they mean by digging more into the information behind the data collection. It was a lot of technical language which I found difficult to deal with when I first started collecting it.
- This data supports the story I'm telling by showing regional overviews of telehealth access.

In [46]:
import pandas as pd
dfRaw2 = pd.read_csv('Data1 - Sheet1.csv')

In [47]:
dfRaw2.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Characteristics of health centers by percentag...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,No. (%) of health centers,NaN,NaN,Bivarate association for reporting >30% telehe...,NaN,NaN
3,NaN,NaN,NaN,NaN,# of visits by telehealth,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Characteristic,NaN,NaN,No. (column %),0%,">0%, <30%",>30%,Prevalence ratio (95% CI),NaN,P-value
6,Total,NaN,NaN,"1,009 (100)",46 (4.6),513 (50.8),450 (44.6),NaN,NaN,NaN
7,Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Northeast,NaN,NaN,164 (16.3),4 (2.4),68 (41.5),92 (56.1),1.81 (1.47-2.22),NaN,<0.0001
9,Midwest,NaN,NaN,206 (20.4),10 (4.9),120 (58.3),76 (36.9),1.19 (0.93-1.51),NaN,NaN

In [48]:
dfRaw2.tail(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
17,Full capacity,NaN,NaN,368 (36.5),31 (8.4),204 (55.4),133 (36.1),Referent,NaN,<0.0001
18,95% capacity,NaN,NaN,412 (40.8),10 (2.4),220 (53.4),182 (44.2),1.22 (1.03-1.45),NaN,NaN
19,< 90% capacity,NaN,NaN,229 (22.7),5 (2.2),89 (38.9),135 (59.0),1.63 (1.37-1.94),NaN,NaN
20,Weekly visits before the COVID-19 pandemic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Decrease,NaN,NaN,828 (81.6),43 (5.2),408 (49.6),372 (45.2),Referent,NaN,0.71
22,No change,NaN,NaN,82 (8.1),2 (2.4),45 (54.9),35 (42.7),0.94 (0.73-1.23),NaN,NaN
23,Increase,NaN,NaN,104 (10.3),1 (1.0),60 (57.7),43 (41.3),0.91 (0.72-1.16),NaN,NaN
24,Personal protective equipment (PPE) shortage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Yes,NaN,NaN,121 (12.0),6 (5.0),69 (57.0),46 (38.0),0.84 (0.66-1.06),NaN,0.12
26,No,NaN,NaN,888 (88.0),40 (4.5),444 (50.0),404 (45.5),Referent,NaN,NaN

In [49]:
dfRaw2.shape

(27, 10)

### Tidied Dataset

In [50]:
import pandas as pd

In [52]:
dfTidied2 = pd.read_csv("Data1 - Tidied - Sheet1.csv")

In [53]:
dfTidied2.head(10)

,"Characteristics of health centers by percentage of visits provided using telehealth and factors associated with telehealth expansion (N=1,009) - Health Center COVID-19 Survey, United States, July 11-17, 2020",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,No. (%) of health centers,NaN,NaN,Bivarate association for reporting >30% telehe...,NaN,NaN
2,NaN,NaN,NaN,NaN,# of visits by telehealth,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Characteristic,NaN,NaN,No. (column %),0%,">0%, <30%",>30%,Prevalence ratio (95% CI),NaN,P-value
5,Total,NaN,NaN,"1,009 (100)",46 (4.6),513 (50.8),450 (44.6),NaN,NaN,NaN
6,Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Northeast,NaN,NaN,164 (16.3),4 (2.4),68 (41.5),92 (56.1),1.81 (1.47-2.22),NaN,<0.0001
8,Midwest,NaN,NaN,206 (20.4),10 (4.9),120 (58.3),76 (36.9),1.19 (0.93-1.51),NaN,NaN
9,South,NaN,NaN,338 (33.5),20 (5.9),213 (63.0),105 (31.1),Referent,NaN,NaN

In [54]:
dfTidied2.tail(10)

,"Characteristics of health centers by percentage of visits provided using telehealth and factors associated with telehealth expansion (N=1,009) - Health Center COVID-19 Survey, United States, July 11-17, 2020",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
16,Full capacity,NaN,NaN,368 (36.5),31 (8.4),204 (55.4),133 (36.1),Referent,NaN,<0.0001
17,95% capacity,NaN,NaN,412 (40.8),10 (2.4),220 (53.4),182 (44.2),1.22 (1.03-1.45),NaN,NaN
18,< 90% capacity,NaN,NaN,229 (22.7),5 (2.2),89 (38.9),135 (59.0),1.63 (1.37-1.94),NaN,NaN
19,Weekly visits before the COVID-19 pandemic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Decrease,NaN,NaN,828 (81.6),43 (5.2),408 (49.6),372 (45.2),Referent,NaN,0.71
21,No change,NaN,NaN,82 (8.1),2 (2.4),45 (54.9),35 (42.7),0.94 (0.73-1.23),NaN,NaN
22,Increase,NaN,NaN,104 (10.3),1 (1.0),60 (57.7),43 (41.3),0.91 (0.72-1.16),NaN,NaN
23,Personal protective equipment (PPE) shortage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Yes,NaN,NaN,121 (12.0),6 (5.0),69 (57.0),46 (38.0),0.84 (0.66-1.06),NaN,0.12
25,No,NaN,NaN,888 (88.0),40 (4.5),444 (50.0),404 (45.5),Referent,NaN,NaN

In [55]:
dfTidied2.shape

(26, 10)